### ISSUE TITLE
For every reference, a second line should be drawn showing what read/write access dereferencing it might yield

### ISSUE THREAD

**Issue by gab-umich** [fplab/rust-resource-timeline#25]
First, we should make a separate function that is responsible for `dereference-state-calculation`. 
(tag a commit at this point if possible)
Starting from there, enrich the data-structure as we go, and then design in SVG how we want it to look. 
(tag a commit at this point if possible)
The last step is to complete the up-dated left_panel.rs
(tag a commit at this point if possible)

**Comment by marcelo-a** [comment]
Second line implementation under construction in branch `secexp`

**Comment by marcelo-a** [comment]
Fixed by commit 409b79e90626a78c9e237cd0ed09ce036888a568
