### ISSUE TITLE
Hover message when user hover over Event Dot

### ISSUE THREAD

**Issue by gab-umich** [fplab/rust-resource-timeline#27]
While this is implemented, the following questions should be answered:

What are the different kinds of Event Dot? What hover-message template do we use for each kind? What are something that we want to convey but lack of information?

**Comment by yingying2000** [comment]
Fixed by  commit [https://github.com/fplab/rust-resource-timeline/commit/61a5374523178e5f929ca8ca206e86dbc8405874](url)
