### ISSUE TITLE
Hover message when user hover over any vertical line

### ISSUE THREAD

**Issue by gab-umich** [fplab/rust-resource-timeline#28]
While this is implemented, the following questions should be answered:

What are the different kinds of Vertical Line? Is there an exact one-to-one relation between that and the State we defined? What templates do we use for each kind? What are something that we want to convey but lack of information?

**Comment by yingying2000** [comment]
fixed by commit [https://github.com/fplab/rust-resource-timeline/commit/9eedd182a3f4051482267f002bbe3f209ca2553f](url)
