### ISSUE TITLE
Add command to compile all examples

### ISSUE THREAD

**Issue by marcelo-a** [fplab/rust-resource-timeline#33]

**Comment by yingying2000** [comment]
Just run "cargo test".

**Comment by yingying2000** [comment]
"cargo test" actually checks whether or not all examples can compile and tests independently, so the output ("rendering.svg") will not actually show up. There isn't a flag written for "cargo"

**Comment by yingying2000** [comment]
"cargo test" actually checks whether or not all examples can compile and tests independently, so the output ("rendering.svg") will not actually show up. There isn't a flag written for "cargo run" or "cargo run --example" to execute all examples. 
A possible fix is to use cargo-do in https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands, which requires installing and also all commands we want to run as a string separated by commas. This is probably not easier than run all the examples by hand.

Reopen this issue if there's anything concerning.

**Comment by marcelo-a** [comment]
Note: "cargo build --examples" builds all commands in [[example]] target bin; however, it does not run the commands.
