### ISSUE TITLE
what should return line and go out of scope line be

### ISSUE THREAD

**Issue by rinshankaihou** [fplab/rust-resource-timeline#34]
Consider this 
```rust
   fn blah {
   s //line 2, Event::Move / return value
   } //line 3, Event::GoOutOfScope
```

would it confuse people if we draw events where it moves out as return value, and then go out of scope at the next line?

**Comment by gab-umich** [comment]
Good question! Sorry for not spotting it earlier. 

In this example, it is very clear that the GoOutOfScope cannot possibly be on the third line (with the `}`). Imagine this: if we insert a statement between the line 2 and line 3, it will not have passed through. The rust compiler will yell at us for something like:

> error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `...`

It is most reasonable to build our mental picture that every lifetime must end right at the line a function returns. To address this confusion, I have made the following comment in the data.rs: 
https://github.com/fplab/rust-resource-timeline/blob/734fb81db438071be113739868b7a20debcd2e36/src/data.rs#L214

Thus, we should conclude that `{` and `}` are not the only scope delimiters, at least when we think of lifetime scopes.
