### ISSUE TITLE
Improve visualization layout

### ISSUE THREAD

**Issue by rinshankaihou** [fplab/rust-resource-timeline#41]
1. label should be centered
2. function logo is not very clear, is partially covered in 04_02_09
3. looks like currently, event circle's upmost point is the center of the line, which makes the layout a bit off
4. improve layout for a single file
x                         fn (x: some_type) {
timeline for x      ...

y                         fn (y: some_type) {
timeline for y      ...

**Comment by marcelo-a** [comment]
Fixed 3 in commit: https://github.com/fplab/rust-resource-timeline/commit/8de5777362f7602c8a49e0c961c7a0bda6551500

**Comment by marcelo-a** [comment]
Fixed 1 in some commit: label already centered

**Comment by marcelo-a** [comment]
TODO: Increase line length to view hover messages.

**Comment by marcelo-a** [comment]
Added toggle button in commit: https://github.com/fplab/rust-resource-timeline/commit/734fb81db438071be113739868b7a20debcd2e36
