### ISSUE TITLE
Change hover message on second line for references

### ISSUE THREAD

**Issue by vishnureddy17** [fplab/rust-resource-timeline#74]
Currently, when hovering over the line to the side of variables of reference type, it says "can mutate the resource it refers to" or "cannot mutate the reference it refers to" depending on whether it's a mutable borrow. 

We should change it to "can mutate *r1" or "cannot mutate *r1" (where r1 is the reference) to match what we said in the paper. 

![IMG_0004](https://user-images.githubusercontent.com/30186564/94575069-d2efe900-0241-11eb-8e5d-a29c8b752e0e.jpg)

**Comment by marcelo-a** [comment]
Fixed by commit: 39d77f654116c52116facf70229453d6c54be3dc
